Just-Jojo/JojoCogs

- alliance/__init__.py
- alliance/alliance.py
- alliance/allianceembed.py
- alliance/info.json
- mcoc/__init__.py
- mcoc/constants.py
- mcoc/info.json
- mcoc/mcoc.py
- mcoc/mcoc_v2.py
These cogs have logically become inscrutable for me to continue working on them. Seeing as you make the majority of edits for these cogs, I thought it'd be better to pass these over for you to manage. Besides, seeing as I've quit MCOC, it bores me to have to make code on it's matter.
If you approve of this, I can remove these cogs from my repo.
I think the problem is that we both code slightly different. Both of our code works, but if you look at a X cog on my repo, its actually quite different to how you would tackle X project.
Additionally, by having to PR everything, and seeing as I don't want to develop these cogs anymore, its development is being decelerated for its demand from our users.
> Alliance and MCOC Cog Repo Merge

- mjolnir/mjolnir.py
Docstrings, and also a small typo in the leaderboard command.
> [Mjolnir] Docstrings and small typo

- todo/todo.py
Few improvements which will soften the tone of the attributes in the help menu, as well as fixes for double colon which really got my OCD. :D
> UI Improvements for attributes

- todo/todo.py
- todo/utils.py
Refactors todo and adds some more customizable settings. I have tested this so that's cool >.>
> Todo refactor

- todo/todo.py
I assume this is what you wanted 😄
> [ToDo] Fixes for the elif statement

- README.md
Added an image for my cogs to make the readme look cooler?
> [Meta] Add an image to look hip?

- brownies/brownies.py
- calculations/calculations.py
- cyclestatus/cycle_status.py
- cyclestatus/info.json
- cyclestatus/menus.py
- depypher/depypher.py
- todo/commands/deleting.py
- todo/commands/examples.py
- todo/commands/todo_settings.py
- todo/todo.py
- todo/utils.py
Changes the doc string license to a comment
Updates `cyclestatus` cog to use jojo_utils
> [Meta] License comments (retry :D)

- todo/CHANGELOG.md
- todo/commands/abc/mixin.py
- todo/commands/examples.py
- todo/commands/todo_settings.py
- todo/todo.py
Caches settings to reduce config calls. Really just a small optimization but could come in handy later on. :)
> [ToDo] Cache settings!

- advancedblacklist/advanced_blacklist.py
> [AdvancedBlacklist] Add reason and local blacklist commands

- todo/commands/__init__.py
- todo/commands/abc/mixin.py
- todo/commands/search.py
- todo/todo.py
Searches the todo list for words or regex patterns
> [ToDo] Search todos for a word/regex pattern

- collectibles/__init__.py
- collectibles/collectibles.py
- collectibles/info.json
- collectibles/utils.py
> Collectibles :D

- todo/commands/examples.py
- todo/commands/todo_settings.py
- todo/todo.py
- todo/utils.py
As the title suggests, this pr adds custom colour support for todo embeds
> [ToDo] Add custom colours for todo lists

- cyclestatus/cycle_status.py
Did this from my phone lol, I'll finish the docstrings and stuff tomorrow.
> [CycleStatus] Add prefix variable

- advancedblacklist/advanced_blacklist.py
This adds the option to add a pattern to a cache to blacklist users by their names. This supports regex
> [AdvancedBlacklist] Add names as a blacklist option as well.

- brownies/brownies.py
> [Brownies] Fix [botname] in cog docstring

- todo/todo.py
Caches todo and completed lists. I also added `suggesters` and update the suggestions command (and added a suggesters command)
> [ToDo] V1.2.13 Cache todo lists

- updateutils/__init__.py
- updateutils/info.json
- updateutils/update.py
Adds update utils, a cog designed for updating my utils :kappa:
> [UpdateUtils]

- ducks/info.json
> [Ducks] Hide from index

- .github/pull_request_template.md
Add an "other" option in the PR template for PRs relating to the repository, or which do not fit into any of the provided categories.
> [Meta] Add "other" option in PR template

- README.md
Added ``ducks`` and ``updateutils`` to the cogs list. I've marked Ducks as unapproved (``O``) seeing as you wished to hide it from the index.
> [Meta] Update cogs list

- todo/commands/todo_settings.py
- todo/todo.py
> [ToDo] Togglable timestamps

- todo/commands/abc.py
- todo/commands/examples.py
- todo/commands/search.py
- todo/commands/todo_settings.py
- todo/todo.py
- todo/utils.py
Allows users to disable non-embedded timestamps in their messages
> [ToDo] Togglable timestamps (co-authored by Kreusada)

- advancedinvite/advanced_invite.py
- advancedinvite/utils.py
Adds more customization to invite by allowing bot owners to set different values for embeds and such
> [AdvancedInvite] Invite settings

- README.md
Change the README for UpdateUtils to remove the second S in "updates"
> [README] Remove second S

- .github/ISSUE_TEMPLATE/config.yml
Disallow blank issues so that all issues can follow the schema of bug reports or feature requests. Add a contact link directing to the support server for further assistance
> Add config to avoid misusage of issue templates

- README.md
If the https isn't provided it redirects to the repository with the link content after it (404)
> Fix support server URL

- ducks/ducks.py
Send the exceptions content instead of a new string. The exception's being casted but is never actually used in the except block
> [Ducks] v0.1.2 Make use of the APIError exception

- advancedblacklist/advanced_blacklist.py
- advancedblacklist/converters.py
- advancedinvite/advanced_invite.py
- brownies/brownies.py
- brownies/converters.py
- brownies/info.json
- collectibles/collectibles.py
- cyclestatus/cycle_status.py
- depypher/depypher.py
- ducks/ducks.py
Various touch-ups and some refactoring :D
> Cog refactor

- todo/utils/cache.py
> [ToDo] Remove print statement in caching function

- todo/core.py
Adds the latest users who have suggested something for ToDo. (EVOLVE#8888 and skylarr#6666)
> [ToDo] Add new suggestors

- advancedinvite/advanced_invite.py
> [AdvancedInvite] Code formatting

- errorblacklist/__init__.py
- errorblacklist/api.py
- errorblacklist/errorblacklist.py
- errorblacklist/info.json
- errorblacklist/menus.py
- errorblacklist/utils.py
Error blacklist allows the bot owner to setup a listener to blacklist users if they use a command that errors too many times in 24 hours.
> [ErrorBlacklist] Create Error Blacklist :D

- errorblacklist/errorblacklist.py
Checks if a command is being handled by itself, and ignores a set type of errors.
Sorry for not catching this in review :p
> [ErrorBlacklist] Stop all commands from falsely being 'errored'

- errorblacklist/errorblacklist.py
> [ErrorBlacklist] better impl

- errorblacklist/errorblacklist.py
pro tip: don't blindly copy and paste things
> [ErrorBlacklist] typo

- todo/commands/settings.py
- todo/consts.py
- todo/core.py
- todo/utils/api.py
- todo/utils/formatting.py
Allows users to set custom emojis for their todo lists, providing that the bot can use them
> [ToDo] Add custom emojis for todo

- todo/commands/__init__.py
- todo/commands/search.py
- todo/core.py
- todo/utils/api.py
Readds `[p]todo search` to todo because I'm not smart :D
> [ToDo] Todo search

- advancedinvite/advanced_invite.py
- cmdlogger/converters.py
- cmdlogger/core.py
- cyclestatus/cycle_status.py
- errorblacklist/errorblacklist.py
Makes some of the changes suggested in the review of my cogs
> Review changes

- cyclestatus/cycle_status.py
Since `cyclestatus settings` had `status list` in the settings command seems to be wrongly so i added to the correct way. lmk if you want the alias to be there instead.
See [here for referance](https://discord.com/channels/240154543684321280/240212783503900673/989398440440115210)
> Update corrections in settings command.

- todo/utils/menus.py
This PR fixes the interaction fails from the todo menu buttons.
> Fix failing button interactions.
